name: csp
version: 0.1.1
description: Reads and writes Content Security Policy (CSP) strings.
homepage: https://github.com/dint-dev/csp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  kind: ^0.5.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5